volumes:
    builder-data: {}

services:
    builder:
        build:
            context: services/php
            target: builder
        depends_on:
            - postgres
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            - UID=${USER_ID}
            # The following list contains the common environment variables exposed by CI platforms
            - GITHUB_ACTIONS
            - CI # Travis CI, CircleCI, Cirrus CI, Gitlab CI, Appveyor, CodeShip, dsari
            - CONTINUOUS_INTEGRATION # Travis CI, Cirrus CI
            - BUILD_NUMBER # Jenkins, TeamCity
            - RUN_ID # TaskCluster, dsari
        volumes:
            - "builder-data:/home/app"
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            - "../..:/var/www:cached"
        profiles:
            - default
