version: '3.7'

volumes:
    builder-data: {}

services:
    php-base:
        build: services/php-base

    builder:
        build: services/builder
        depends_on:
            - postgres
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
            # The following list contains the common environment variables exposed by CI platforms
            - GITHUB_ACTIONS
            - CI # Travis CI, CircleCI, Cirrus CI, Gitlab CI, Appveyor, CodeShip, dsari
            - CONTINUOUS_INTEGRATION # Travis CI, Cirrus CI
            - BUILD_NUMBER # Jenkins, TeamCity
            - RUN_ID # TaskCluster, dsari
        volumes:
            - "../../${PROJECT_DIRECTORY}:/home/app/application:cached"
            - "${COMPOSER_CACHE_DIR}:/home/app/.composer/cache"
            - "builder-data:/home/app"
